import React, { useState } from 'react';
import {
  Phone,
  CheckCircle2,
  Shield,
  ExternalLink,
  Cpu,
  FileText,
  X,
  Lock,
  Database,
  Scale,
  Award,
} from 'lucide-react';
import { SurakshaLogo, DigitalIndiaBadge } from './SurakshaLogo';

import { UserProfile } from '../types';

interface FooterViewProps {
  currentUser?: UserProfile | null;
  onNavigate: (view: string) => void;
  onOpenSmartContractModal?: () => void;
}

interface StatutoryModalContent {
  title: string;
  badge: string;
  actCode: string;
  summary: string;
  clauses: { code: string; title: string; desc: string }[];
}

export const FooterView: React.FC<FooterViewProps> = ({
  currentUser,
  onNavigate,
  onOpenSmartContractModal,
}) => {
  const [activeStatutoryModal, setActiveStatutoryModal] = useState<StatutoryModalContent | null>(
    null
  );

  const openLegalModal = (type: string) => {
    switch (type) {
      case 'IT_ACT':
        setActiveStatutoryModal({
          title: 'Information Technology Act, 2000 (Amended 2008)',
          badge: 'Parliament of India Statutory Act',
          actCode: 'IT Act, 2000 • § 43A & § 65B',
          summary:
            'Legal recognition and evidentiary admissibility of electronic records and cryptographic hash verification in Indian courts of law.',
          clauses: [
            {
              code: 'Section 43A',
              title: 'Compensation for Failure to Protect Data',
              desc: 'Mandates strict implementation and maintenance of reasonable security practices and procedures for sensitive personal data or information (SPDI). Suraksha Sathi implements FIPS 140-2 Level 3 HSM and SHA-256 zero-trust architecture to ensure zero data leakage.',
            },
            {
              code: 'Section 65B (Admissibility of Electronic Records)',
              title: 'Special Provisions as to Evidence Relating to Electronic Record',
              desc: 'Enforces that any electronic output containing cryptographic SHA-256 Merkle proofs generated by Suraksha Sathi is deemed an admissible document in civil and criminal proceedings under the Indian Evidence Act, 1872 without requiring primary paper production.',
            },
          ],
        });
        break;

      case 'DPDP_ACT':
        setActiveStatutoryModal({
          title: 'Digital Personal Data Protection (DPDP) Act, 2023',
          badge: 'Statutory Data Privacy Regime',
          actCode: 'Act No. 22 of 2023 • Ministry of Law & Justice',
          summary:
            'Comprehensive framework regulating processing of digital personal data while respecting individuals’ right to privacy and legitimate governance purposes.',
          clauses: [
            {
              code: 'Section 6 & 7',
              title: 'Zero-PII On-Chain Architecture',
              desc: 'Under Suraksha Sathi, no Personally Identifiable Information (Aadhaar, PAN, phone, physical address) is stored on the public blockchain. Only one-way SHA-256 cryptographic hashes and anonymous W3C DIDs are anchored on-chain.',
            },
            {
              code: 'Section 11 & 12',
              title: 'Data Principal Sovereign Rights',
              desc: 'Every citizen retains self-sovereign control over their digital certificates and deed credentials with cryptographically enforceable verification permissions.',
            },
          ],
        });
        break;

      case 'NBF_MEITY':
        setActiveStatutoryModal({
          title: 'National Blockchain Framework (NBF)',
          badge: 'MeitY Sovereign Architecture',
          actCode: 'MeitY Strategic Framework for Blockchain',
          summary:
            'Enabling a resilient and unified sovereign blockchain ecosystem across India for digital governance, asset integrity, and fraud eradication.',
          clauses: [
            {
              code: 'Pillar I',
              title: 'Permissioned Distributed Ledger Governance',
              desc: 'Federated consensus architecture linking state registries, central departments, and universities under trusted statutory validator nodes.',
            },
            {
              code: 'Pillar II',
              title: 'Soulbound Non-Transferable Deeds',
              desc: 'Ensures property records, FD receipts, and degrees cannot be maliciously sold or double-transferred, eradicating fraudulent conveyance.',
            },
          ],
        });
        break;

      case 'ZERO_PII':
        setActiveStatutoryModal({
          title: 'Zero-PII Cryptographic Privacy Engine',
          badge: 'Privacy-by-Design Architecture',
          actCode: 'zk-SNARK & SHA-256 Zero Exposure',
          summary:
            'Guarantees mathematical verification of authenticity without exposing the contents of deeds or citizen identities.',
          clauses: [
            {
              code: 'Protocol 1',
              title: 'SHA-256 Document Fingerprint',
              desc: 'Uploaded PDF/JPEG is hashed on the client device. Only the 64-character hexadecimal digest is submitted to the verification contract.',
            },
            {
              code: 'Protocol 2',
              title: 'Zero-Knowledge Proof Attestation',
              desc: 'Verifiers can confirm a land deed is authentic and encumbrance-free without revealing plot coordinates or purchase price to third parties.',
            },
          ],
        });
        break;

      case 'DEED_HASHING':
        setActiveStatutoryModal({
          title: 'SHA-256 256-Bit Cryptographic Hashing Standard',
          badge: 'NIST FIPS 180-4 Standard',
          actCode: 'Secure Hash Algorithm 256-Bit',
          summary:
            'Collision-resistant cryptographic hashing that generates a unique 256-bit identifier for any digital file. Altering even a single pixel or character invalidates the hash entirely.',
          clauses: [
            {
              code: 'Security Proof',
              title: '2^256 Preimage Resistance',
              desc: 'Computationally impossible to reverse-engineer original documents or forge counterfeit documents that produce the same digest.',
            },
          ],
        });
        break;

      case 'CAG_AUDIT_TRAIL':
        setActiveStatutoryModal({
          title: 'CAG Statutory Cryptographic Audit Trail',
          badge: 'Article 149 of Constitution of India',
          actCode: 'CAG (DPC) Act, 1971 • Public Ledger Integrity Mandate',
          summary:
            'Autonomous constitutional audit framework ensuring real-time verifiability, immutable cryptographic event recording, and forensic tamper oversight across all sovereign registries.',
          clauses: [
            {
              code: 'Article 149 & 151',
              title: 'Constitutional Duties of the CAG',
              desc: 'Empowers the Comptroller & Auditor General to oversee and audit all accounts and statutory deeds of the Union and States. Suraksha Sathi generates live Merkle cryptographic proof batches for direct statutory CAG inspection.',
            },
            {
              code: 'Statutory Hash Ledger',
              title: 'Zero-Tamper Chain of Custody',
              desc: 'Every deed registration, officer attestation, and administrative intervention is etched with a SHA-256 state root anchored onto the Polygon Amoy blockchain with zero possibility of retroactive alteration or deletion.',
            },
            {
              code: 'Forensic Verifiability',
              title: 'Real-Time Tamper Anomaly Alerts',
              desc: 'Integrates automated neural tamper detection flags directly into the CAG Auditor queue for statutory review and legal enforcement.',
            },
          ],
        });
        break;

      case 'RBAC_FRAMEWORK':
        setActiveStatutoryModal({
          title: 'Statutory 4-Tier RBAC Permission & Clearance Framework',
          badge: 'IT Act 2000 § 43A • CERT-In Zero-Trust Security Standard',
          actCode: 'Sovereign Role-Based Access Control Specification v3.2',
          summary:
            'Strict hierarchical permission matrix enforcing least-privilege security clearance, hardware device binding, and administrative authorization protocols.',
          clauses: [
            {
              code: 'Tier 0: Root Sovereign Admin',
              title: 'Hardware-Bound Master Authority (Deep123)',
              desc: 'Highest clearance tier locked exclusively to the designated physical workstation. Sovereign Admin exclusively provisions and authorizes Level 3 CAG Auditors, monitors ledger health, and oversees master security parameters.',
            },
            {
              code: 'Tier 1: CAG Statutory Auditor',
              title: 'Level 3 Constitutional Ledger Oversight',
              desc: 'Audits officer forensic queues, sanctions citizen tamper dispute resolutions, provisions and supervises Level 2 Verification Officers.',
            },
            {
              code: 'Tier 2: Verification Officer',
              title: 'Level 2 Field & Registry Validation',
              desc: 'Validates uploaded property deeds and certificates against state land databases, conducts in-person physical inspections, and forwards complex fraud dossiers to CAG Auditors.',
            },
            {
              code: 'Tier 3: Sovereign Citizen',
              title: 'Self-Sovereign Identity (W3C DID)',
              desc: 'Encrypted personal deed vault, instant cryptographic QR sharing, and soulbound NFT non-transferable certificate management.',
            },
          ],
        });
        break;

      case 'CONSENSUS':
        setActiveStatutoryModal({
          title: 'Polygon Amoy Proof-of-Stake Consensus',
          badge: 'Chain ID 80002 • Energy Efficient & Fast',
          actCode: 'Heimdall & Bor Layer 2 Consensus',
          summary:
            'Ultra-fast 2-second block finality with checkpoint anchoring to Ethereum Mainnet for multi-layer security.',
          clauses: [
            {
              code: 'Validation',
              title: 'Statutory Validator Nodes',
              desc: 'Transactions and deed attestations are cryptographically validated by decentralized validator nodes with sub-cent transaction fees.',
            },
          ],
        });
        break;

      default:
        break;
    }
  };

  return (
    <footer className="bg-[#ecfdf5] border-t-2 border-[#10b981] text-[#1e293b] select-none relative">
      {/* Top Helpline Banner */}
      <div className="border-b border-[#a7f3d0]/60 py-3">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-2.5 text-xs font-medium">
          <div className="flex items-center gap-2">
            <span className="text-sm">🇮🇳</span>
            <span className="font-bold text-slate-900" style={{ fontFamily: 'Arial, sans-serif' }}>
              भारत सरकार
            </span>
            <span className="text-slate-400">•</span>
            <span className="text-slate-800">
              Government of India • Ministry of Electronics & Information Technology (MeitY)
            </span>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-1.5">
              <Phone className="w-3.5 h-3.5 text-[#059669]" />
              <span className="text-slate-700">Toll-Free Helpline:</span>
              <a
                href="tel:8127291476"
                className="font-mono font-bold text-blue-700 hover:text-blue-900 underline"
              >
                8127291476
              </a>
              <span className="px-1.5 py-0.2 rounded text-[9px] font-bold bg-[#1e3a8a] text-white">
                24x7
              </span>
            </div>

            <div className="flex items-center gap-1 text-[#047857]">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span className="text-xs font-semibold">CERT-In Guidelines Aligned</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main 3 Columns with BLUE FONT COLOR on all links */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Column 1: Brand & Mission */}
          <div className="space-y-3.5">
            <SurakshaLogo variant="light" size="md" />
            <div className="pt-1">
              <DigitalIndiaBadge size="sm" />
            </div>

            <p className="text-xs text-slate-700 leading-relaxed">
              An immutable sovereign infrastructure securing digital property deeds, academic
              qualifications, and statutory certificates through W3C Decentralized Identifiers (DID)
              and cryptographic blockchain anchoring.
            </p>

            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md bg-white border border-[#a7f3d0] text-[11px] font-medium text-emerald-900 shadow-2xs">
              <span className="w-2 h-2 rounded-full bg-[#10b981]" />
              <span>Statutory Rule: &ldquo;Register once. Verify forever. Alter never.&rdquo;</span>
            </div>
          </div>

          {/* Column 2: Registry Services - ALL LINKS ACTIVE IN BLUE FONT COLOR */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b border-[#a7f3d0]/60 pb-1.5">
              REGISTRY SERVICES [PORTAL]
            </h4>
            <ul className="space-y-2 text-xs">
              <li>
                <button
                  type="button"
                  onClick={() => onNavigate('TAMPER_DETECTION')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline flex items-center gap-1.5 text-left transition-colors cursor-pointer"
                >
                  <span>AI Tamper Detector & Forensics</span>
                  <span className="px-1 py-0.2 rounded text-[8px] font-black bg-blue-700 text-white uppercase">
                    AI NEW
                  </span>
                </button>
              </li>
              <li>
                <button
                  type="button"
                  onClick={() => onNavigate('VERIFY_ASSET')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors cursor-pointer"
                >
                  Public Cryptographic Verifier
                </button>
              </li>
              {(!currentUser || currentUser.role === 'USER') && (
                <li>
                  <button
                    type="button"
                    onClick={() => onNavigate('CITIZEN')}
                    className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors cursor-pointer"
                  >
                    Citizen Sovereign Vault & Registry
                  </button>
                </li>
              )}
              {currentUser && currentUser.role !== 'USER' && (
                <li>
                  <button
                    type="button"
                    onClick={() => onNavigate('RBAC')}
                    className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors cursor-pointer"
                  >
                    RBAC Statutory Command Center
                  </button>
                </li>
              )}
              <li>
                <button
                  type="button"
                  onClick={() => onNavigate('PUBLIC_LEDGER')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline flex items-center gap-1 text-left transition-colors cursor-pointer"
                >
                  <span>Polygon Amoy Explorer (Chain 80002)</span>
                  <ExternalLink className="w-3 h-3 text-blue-500" />
                </button>
              </li>
            </ul>
          </div>

          {/* Column 3: Statutory Compliance - ALL LINKS ACTIVE IN BLUE FONT COLOR */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b border-[#a7f3d0]/60 pb-1.5">
              STATUTORY COMPLIANCE [LEGAL]
            </h4>
            <ul className="space-y-2 text-xs">
              <li>
                <button
                  type="button"
                  onClick={() => openLegalModal('CAG_AUDIT_TRAIL')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>CAG Cryptographic Audit Trail</span>
                  <ExternalLink className="w-2.5 h-2.5 text-blue-500 shrink-0" />
                </button>
              </li>
              <li>
                <button
                  type="button"
                  onClick={() => openLegalModal('RBAC_FRAMEWORK')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>RBAC Permission Framework</span>
                  <ExternalLink className="w-2.5 h-2.5 text-blue-500 shrink-0" />
                </button>
              </li>
              <li>
                <button
                  type="button"
                  onClick={() => openLegalModal('IT_ACT')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>Information Technology Act, 2000 (§ 43A & § 65B)</span>
                  <ExternalLink className="w-2.5 h-2.5 text-blue-500 shrink-0" />
                </button>
              </li>
              <li>
                <button
                  type="button"
                  onClick={() => openLegalModal('DPDP_ACT')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>Digital Personal Data Protection (DPDP) Act, 2023</span>
                  <ExternalLink className="w-2.5 h-2.5 text-blue-500 shrink-0" />
                </button>
              </li>
              <li>
                <button
                  type="button"
                  onClick={() => openLegalModal('NBF_MEITY')}
                  className="text-blue-600 hover:text-blue-800 font-semibold hover:underline text-left transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <span>National Blockchain Framework (MeitY Aligned)</span>
                  <ExternalLink className="w-2.5 h-2.5 text-blue-500 shrink-0" />
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Bottom Bar */}
      <div className="border-t border-[#a7f3d0] py-4 bg-[#e6f7ef]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-600">
          <div>
            © 2026 Government of India Digital Initiative • Sovereign Asset Integrity Framework •
            All Rights Reserved.
          </div>

          <div className="flex items-center gap-2">
            <div className="px-2.5 py-1 rounded-full bg-white border border-[#a7f3d0] text-xs font-semibold shadow-2xs">
              <span className="w-1.5 h-1.5 rounded-full bg-[#10b981] inline-block mr-1.5" />
              Developed by <span className="font-bold text-[#f97316]">OUTSIDERS</span>
            </div>
            <span className="text-slate-400 hidden sm:inline">•</span>
            <span className="italic text-slate-700 hidden md:inline">
              &ldquo;Register once. Verify forever. Alter never.&rdquo;
            </span>
          </div>
        </div>
      </div>

      {/* STATUTORY DETAIL MODAL */}
      {activeStatutoryModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl border border-slate-200 max-w-lg w-full p-6 space-y-4 shadow-2xl relative">
            <div className="flex items-start justify-between border-b border-slate-100 pb-3">
              <div className="space-y-1">
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-800 uppercase">
                  {activeStatutoryModal.badge}
                </span>
                <h3 className="text-base font-bold text-slate-900">
                  {activeStatutoryModal.title}
                </h3>
                <p className="text-xs text-blue-700 font-mono font-semibold">
                  {activeStatutoryModal.actCode}
                </p>
              </div>

              <button
                onClick={() => setActiveStatutoryModal(null)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg hover:bg-slate-100 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-lg border border-slate-200">
              {activeStatutoryModal.summary}
            </p>

            <div className="space-y-3 max-h-64 overflow-y-auto pr-1">
              {activeStatutoryModal.clauses.map((clause, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl bg-blue-50/50 border border-blue-100 space-y-1"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-[#1e3a8a]">{clause.title}</span>
                    <span className="px-1.5 py-0.2 rounded bg-blue-200/60 text-blue-900 text-[9px] font-mono font-bold">
                      {clause.code}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-700 leading-relaxed">{clause.desc}</p>
                </div>
              ))}
            </div>

            <div className="pt-2 flex items-center justify-end gap-2">
              {(activeStatutoryModal.title.includes('CAG') ||
                activeStatutoryModal.title.includes('RBAC')) && (
                <button
                  type="button"
                  onClick={() => {
                    setActiveStatutoryModal(null);
                    onNavigate('RBAC');
                  }}
                  className="px-4 py-2 bg-emerald-700 hover:bg-emerald-800 text-white rounded-lg text-xs font-bold transition-colors cursor-pointer"
                >
                  {activeStatutoryModal.title.includes('CAG')
                    ? 'Explore CAG Audit Trail'
                    : 'Access RBAC Command Portal'}
                </button>
              )}
              <button
                type="button"
                onClick={() => setActiveStatutoryModal(null)}
                className="px-4 py-2 bg-slate-200 hover:bg-slate-300 text-slate-800 rounded-lg text-xs font-bold transition-colors cursor-pointer"
              >
                Close & Return
              </button>
            </div>
          </div>
        </div>
      )}
    </footer>
  );
};
